name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      # Step 0: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
    
      # Step 1: Create .env file
      - name: Install dependencies
        run: |
          cat <<EOF > .env
          # Application Information
          VITE_BRAND_NAME=${{ vars.VITE_BRAND_NAME }}
          VITE_LOGO_SRC=${{ vars.VITE_LOGO_SRC }}
          # URLs
          VITE_PANEL_DOMAIN=${{ secrets.VITE_PANEL_DOMAIN }}
          VITE_JSON_APPS_URL=${{ secrets.VITE_JSON_APPS_URL }}
          VITE_SUPPORT_URL=${{ secrets.VITE_SUPPORT_URL }}
          # Feature Toggles
          VITE_OFF_SECTIONS=${{ vars.VITE_OFF_SECTIONS }}
          EOF
      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Build the project
      - name: Build project
        run: npm run build

      # Step 4.5: Verify build output
      - name: List build directory
        run: ls -al build/

      # New 5: Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: build/index.html
          retention-days: 5

      # New 6: delete .env
      - name:  Clean up .env
        run: rm -f .env
